[package]
name = "mathilda"
description = ""
version = "0.0.1"
authors = ["Christian Sdunek <me@systemcluster.me>"]
edition = "2018"
publish = false
license = "unlicensed"

[[bin]]
name = "mathilda"
path = "src/main.rs"
[[bin]]
name = "mathilda-gen"
path = "src/main_gen.rs"


[profile.dev]
opt-level = 0
panic = "unwind"
debug = true
debug-assertions = true

[profile.test]
opt-level = 1
debug = true
debug-assertions = true

[profile.release]
opt-level = 3
panic = "abort"
debug = false
debug-assertions = false
lto = "thin"


[dependencies]

# sys crates
derive_more = "0.99.2"
log = "0.4.8"
pretty_env_logger = { git = "https://github.com/seanmonstar/pretty-env-logger" }
#pretty_env_logger = { path = "../pretty-env-logger" }
color-backtrace = "0.3.0"
raw-cpuid = "7.0.3"

# util crates
serde = { version = "1.0.103", features = ["derive"] }
#warmy = "^0.12"
failure = "0.1.6"
itertools = "0.8.2"
rand = "0.7.2"
dirs = "2.0.2"
chrono = "0.4.10"
specs = "0.15.1"
priority-queue = "0.6.0"
pathfinding = "2.0.0"
derivative = "1.0.3"
tokio = { git="https://github.com/tokio-rs/tokio" }
legion = { git = "https://github.com/TomGillen/legion" }

# graphics crates
wgpu = { package="wgpu", git="https://github.com/gfx-rs/wgpu-rs", branch="master" }
winit = { git="https://github.com/rust-windowing/winit", branch="master" }
nalgebra = { version = "0.19.0", features = ["mint"] }
spirv-reflect = "0.2.3"
shaderc = "0.6.1"
image = "0.22.3"
petgraph = "0.4.13"
zerocopy = "0.2.8"
#lyon = "^0.14"
#rusttype = "^0.7"
